trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x.x'  # Replace with the version you need

- script: dotnet restore
  displayName: 'Restore NuGet Packages'

- script: dotnet build --configuration Release --no-restore
  displayName: 'Build Solution'

- script: |
    for project in src/CheckDigit/CheckDigit.csproj src/CheckDigit.Documento/CheckDigit.Documento.csproj; do
      dotnet pack $project --configuration Release --output $(Build.ArtifactStagingDirectory)
    done
  displayName: 'Pack Projects'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'.csproj src/ProjectB/ProjectB.csproj; do
      dotnet pack $project --configuration Release --output $(Build.ArtifactStagingDirectory)
    done
  displayName: 'Pack Projects'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
