trigger: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.100'

- script: dotnet restore
  displayName: 'Restore NuGet Packages'

- script: dotnet test
  displayName: 'Run tests'

- script: dotnet build --configuration Release --no-restore
  displayName: 'Build Solution'

- script: |
    for project in src/CheckDigit/CheckDigit.csproj src/CheckDigit.Documento/CheckDigit.Documento.csproj; do
      dotnet pack $project --configuration Release --output $(Build.ArtifactStagingDirectory)
    done
  displayName: 'Pack Projects'

- script: dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --api-key $(System.AccessToken) --source https://pkgs.dev.azure.com/marcoshidalgonunes/CheckDigit/_packaging/CheckDigit/nuget/v3/index.json
  displayName: 'Push NuGet Package'